### ISSUE TITLE
"Started scraping submissions for 0 solved questions"

### ISSUE THREAD

**Issue by jandonov** [jiachengxu/leetdoad#1]
I keep getting this error when I try to use the script.

```
"Started scraping submissions for 0 solved questions"
```

Even tho I have around 400 solved problems. I wanted to double check if the script is still working? Maybe I am doing something wrong and using the wrong cookie string, but if that's the case the message is a bit misleading.

**Comment by mountainmort** [comment]
@jandono -
I found that when I copied my cookie down from leetcode, the cookie had a section in there along the lines of the following. I had to delete that out of the middle of the cookie and leave the rest intact in order to get it pull my submissions again properly. 

`messages="e8428c4a8ba743eca88d44596e4f9e0716a4c91f$[[\"__json_message\"\0540\05425\054\"Successfully signed in as (username)\"]]"; `

**Comment by jiachengxu** [comment]
I have tested locally, and the full cookie works for me, even with the `messages` part, I think you need to preserve the `"` in the `message` by using single quotes, otherwise, the cookie will be invalid, for example, when you set the env, you can do:
```
 export LEETCODE_COOKIE='<Your Cookie>'
```
Using single quotes. 
Closing it for now, but free feel to reopen it.
